# Site settings
title: "brain-computer music interfacing"
description: "brain-computer music interfacing blog for a doctoral research"
keywords:
- tedor, tedör, krisztian hofstadter, brain-computer music interfacing

baseurl: "" # required if used under gh-pages branch, else (under master branch) just leave empty/blank

# Build settings
permalink: /:title/

## exclude
exclude:
- README.md
- CNAME

plugins:
  - jekyll-sitemap

# Sitemap (see sitemap.xml)
sitemap:
  changefreq: weekly

# Third-party services
# just leave empty to disable it
google_analytics: UA-125796353-4
disqus_shortname: bcmi-khofstadter

### exclude
exclude:
- README.md
- CNAME

### include
include:
  - .htaccess

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: posts
    values:
      layout: post
